<a href="https://colab.research.google.com/github/Arindam2002/tensorflow_learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Introduction to Tensors

### Creating tensors with `tf.constant`

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
# Creating tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# No. of dimensions of a tensor
scalar.ndim

0

In [4]:
# Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Dimension of a vector
vector.ndim

1

In [6]:
# Matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Dimension of a matrix
matrix.ndim

2

In [8]:
# Another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# No. of dimensions of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

### Creating tensors with `tf.variable`

In [12]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# change one of the elements using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [14]:
# Creating 2 random but same tensors
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [15]:
# Shuffle a tensor (Valuable for when u want to shuffle your data so that the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [16]:
tf.random.set_seed(42)  # global level random seed
tf.random.shuffle(not_shuffled, seed = 42)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

> Rule: "If both the global and the operation seed are set: both seeds are used in conjunction to determine the random sequence"

### Other ways to make tensors

In [17]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
# Create a tensor of all zeroes
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turning numpy arrays to tensors

The main difference b/w NumPy arrays & tensors is that tensors can be run on a GPU

In [19]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)    #numpy array b/w 1 - 24
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2, 3, 4))   # keep in mind that 2*3*4 equals the original size of array
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [21]:
A.ndim, B.ndim

(1, 3)

### Getting information from tensors

* Shape - `tensor.shape`
* Rank - `tensor.ndim`
* Axis or dimension - `tensor[0], tensor[:, 1]...`
* Size - `tf.size(tensor)`

In [22]:
# Create a rank 4 tensor (i.e. 4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [24]:
#  Get various attributes of our tensor
print("Data type of every element: ", rank_4_tensor.dtype)
print("No. of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total no. of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total no. of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Data type of every element:  <dtype: 'float32'>
No. of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total no. of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total no. of elements in our tensor:  120


### Indexing tensors

Tensors can be indexed just like python lists

In [25]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [26]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
#  Get first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [30]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor, axis=0)  # expand the final 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**
`+`, `-`, `*`, `/`

In [33]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10  # Doesn't change original tensor until "tensor = tensor + 10" is performed
# Similar for the rest

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [34]:
# Built-in functions can also be used - Much faster
tf.multiply(tensor, 10) # original tensor will still be unchanged 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix multiplication**

Using tensorflow - `tf.matmul(tensor1, tensor2)`

Using python operator - `tensor @ tensor`

In [35]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [36]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [37]:
X = tf.constant([[2, 3],
                 [4, 5],
                [6, 7]])
Y = tf.constant([[1, 6],
                 [2, 5],
                [3, 4]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5],
        [6, 7]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 6],
        [2, 5],
        [3, 4]], dtype=int32)>)

In [38]:
# To multiply X & Y we need to reshape the tensor according to the rules of matrix multiplication
Y_reshaped = tf.reshape(Y, shape=(2, 3))
Y_reshaped

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 6, 2],
       [5, 3, 4]], dtype=int32)>

In [39]:
# multiplying X with reshaped Y
tf.matmul(X, Y_reshaped)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 21, 16],
       [29, 39, 28],
       [41, 57, 40]], dtype=int32)>

In [40]:
X @ Y_reshaped

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 21, 16],
       [29, 39, 28],
       [41, 57, 40]], dtype=int32)>

In [41]:
# Transpose of a matrix
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [3, 5, 7]], dtype=int32)>

**Dot product**

Matrix multiplication is aka dot product.

Matrix multiplication can be performed using:
* `tf.matmul()`
* `tf.tensordot()`

In [42]:
# Perform dot product on X & Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 56],
       [34, 71]], dtype=int32)>

In [43]:
# Multiply X & Y(transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 19, 18],
       [34, 33, 32],
       [48, 47, 46]], dtype=int32)>

In [44]:
# Multiply X & Y(reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 21, 16],
       [29, 39, 28],
       [41, 57, 40]], dtype=int32)>

In [45]:
print("Normal Y:")
print(Y, "\n")
print("Reshaped Y to (2, 3):")
print(tf.reshape(Y, shape=(2, 3)), "\n")
print("Transposed Y:")
print(tf.transpose(Y), "\n")

Normal Y:
tf.Tensor(
[[1 6]
 [2 5]
 [3 4]], shape=(3, 2), dtype=int32) 

Reshaped Y to (2, 3):
tf.Tensor(
[[1 6 2]
 [5 3 4]], shape=(2, 3), dtype=int32) 

Transposed Y:
tf.Tensor(
[[1 2 3]
 [6 5 4]], shape=(2, 3), dtype=int32) 



⚒️ Transpose rather than reshape if while matrix multiplication the tensors have difference in size

### Changing the datatype of a tensor

In [46]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [47]:
C = tf.constant([1, 2])
C.dtype

tf.int32

In [48]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
B.dtype, D.dtype

(tf.float32, tf.float16)

In [49]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
C.dtype, E.dtype

(tf.int32, tf.float32)

### Aggregating tensors

In [50]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [51]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [52]:
# Create a random tensor with values b/t 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 5, 64, 45, 78, 96, 11, 67, 39, 47, 94, 26, 17, 15, 41, 37, 29,  1,
       93, 14, 32, 15, 47, 98, 42, 16, 92, 89, 70, 58, 64, 97, 42, 40, 15,
       12, 42, 21,  8, 61,  5, 39, 78, 96, 70, 40, 69, 88, 37, 77, 75])>

In [53]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [54]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [55]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [56]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [57]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2454>

In [58]:
# Find the variance of a tensor
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=876>

In [59]:
# OR
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))  # Has to be casted in float datatype, else doesn't work

<tf.Tensor: shape=(), dtype=float16, numpy=877.0>

In [60]:
# Find the standart deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))  # Has to be casted in float datatype, else doesn't work

<tf.Tensor: shape=(), dtype=float16, numpy=29.61>

### Find the positional maximum and minimum of a tensor

In [61]:
# Creating a random tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [62]:
# Positional max    (returns index of max value)
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [63]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [64]:
# Find max in tensor using aggregation
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [65]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [66]:
# Positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [67]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [68]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [69]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [70]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One hot encoding

In [71]:
# Create list of indices
some_list = [0, 1, 2, 3]    # say, red, green, blue, purple

# One hot encode our indices
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [72]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=len(some_list), on_value="yes", off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

### Squaring, log, square root

In [73]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [74]:
# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [75]:
# Square root
tf.math.sqrt(tf.cast(H, dtype=tf.float32))     # sqrt doesn't support int32 values so had to cast the tensor to float

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [76]:
# Log
tf.math.log(tf.cast(H, dtype=tf.float32))   # log doesn't support int32 values so had to cast the tensor to float

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors  and NumPy

Tensorflow interacts beautifully with NumPy arrays

In [77]:
# Creating a tensor directly from numpy arrray
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [78]:
# Converting the tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [79]:
# Converting tensor J to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [80]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [81]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [82]:
!nvidia-smi

Thu Jun 30 18:57:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    26W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------